backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "events_data"
    label: "Διαχείριση Εκδηλώσεων"
    files:
      - label: "Λίστα Εκδηλώσεων"
        name: "events_list"
        file: "data/events.json"
        fields:
          - label: "Εκδηλώσεις"
            name: "events"
            widget: "list"
            fields:
              - {label: "Τίτλος Εκδήλωσης", name: "title", widget: "string"}
              - {label: "Ημερομηνία", name: "date", widget: "datetime", date_format: "DD/MM/YYYY"}
              - {label: "Περιγραφή", name: "description", widget: "text"}
              - {label: "Αφίσα (Προαιρετικό)", name: "image", widget: "image", required: false}
